config/routes.rb
Rails.application.routes.draw do
  root 'books#welcome'
  resources :books

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.search(search)
    where("name LIKE ?", "%#{search}%").first 
  end

  def recommended_books

    @user_id = self.id

    @favorite_books = Like.where(user_id: @user_id).map do |x|
      Book.find(x.book_id)
    end

    @likes_in_commom_user_and_other_users = @favorite_books.map do |x|
      Like.where(book_id: x.id).map do |y|
        y
      end.flat_map {|i| i}
    end

    @similar_users = @likes_in_commom_user_and_other_users.flat_map do |i| 
      i
    end.map do |x|
      x.user_id if x.user_id != @user_id
    end

    @similar_users_ids = []
    @similar_users.map do |x|
      if x != nil
        @similar_users_ids << x
      end
    end
    
    @similar_users_likes = @similar_users_ids.map do |x|
      Like.where(user_id: x).map do |y|
        y
      end
    end.flat_map do |i| 
      i
    end

    @similar_users_books = @similar_users_likes.map do |x|
      Book.find(x.book_id).title
    end

    @user_books = @favorite_books.map do |title|
      title.title
    end

    @recommendations = @similar_users_books - @user_books

  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def welcome
  end

  def index
    
    @user = User.search(params[:search])

    @favorite_books = Like.where(user_id: @user.id).map do |x|
      Book.find(x.book_id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/index.html.erb
<p><h1 id="greetings"> Hello, <%= @user.name %>! </h1></p>

<h2 id="list_titles"> You've liked these books: </h2>
<p>
  <% @favorite_books.map do |x| %>
  <p>
    <%= x.title %>
  </p>
  <% end %>
</p>

<h2 id="list_suggestions">Here some reading suggestions based on people with similar taste:</h2>

<p id="recommendations">
  <% @user.recommended_books.map do |title| %>
  <p>
    <%= title %>
  </p>
  <% end %>
</p>

app/views/books/welcome.html.erb
<p><h1> Inform your name to get reading suggestions: </h1></p>

<%= form_tag(books_path, :method => 'get', id: "search-form") do %>
  <p> 
    <%= text_field_tag :search, params[:search], placehorlder: "Search User" %>
    <%= submit_tag "Go", :name => nil %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recommendation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>